# Make Single Dataset out of Disparate Input and Output Pieces

In [50]:
# importing tools
import numpy as np
import math
import scipy
import matplotlib.pyplot as plt

In [51]:
#MAKING MY DATASET
inputs = np.load("/home/nowickr/pnevo/PNevo/astr8070/MPARs_for_Project/inputs_arr.npy")
print(inputs)

[[4.00e+00 1.00e-01 1.20e+02]
 [4.00e+00 1.00e-01 1.50e+02]
 [4.00e+00 1.00e-01 1.60e+02]
 [4.00e+00 1.00e-01 1.70e+02]
 [4.00e+00 1.00e-01 1.75e+02]
 [5.00e+00 1.00e-01 1.20e+02]
 [5.00e+00 1.00e-01 1.50e+02]
 [5.00e+00 1.00e-01 1.60e+02]
 [5.00e+00 1.00e-01 1.70e+02]
 [5.00e+00 1.00e-01 1.75e+02]
 [6.00e+00 1.00e-01 1.20e+02]
 [6.00e+00 1.00e-01 1.50e+02]
 [6.00e+00 1.00e-01 1.60e+02]
 [6.00e+00 1.00e-01 1.70e+02]
 [6.00e+00 1.00e-01 1.75e+02]
 [7.00e+00 1.00e-01 1.20e+02]
 [7.00e+00 1.00e-01 1.50e+02]
 [7.00e+00 1.00e-01 1.60e+02]
 [7.00e+00 1.00e-01 1.70e+02]
 [7.00e+00 1.00e-01 1.75e+02]
 [8.00e+00 1.00e-01 1.20e+02]
 [8.00e+00 1.00e-01 1.50e+02]
 [8.00e+00 1.00e-01 1.60e+02]
 [8.00e+00 1.00e-01 1.70e+02]
 [8.00e+00 1.00e-01 1.75e+02]
 [9.00e+00 1.00e-01 1.20e+02]
 [9.00e+00 1.00e-01 1.50e+02]
 [9.00e+00 1.00e-01 1.60e+02]
 [9.00e+00 1.00e-01 1.70e+02]
 [9.00e+00 1.00e-01 1.75e+02]
 [1.00e+01 1.00e-01 1.20e+02]
 [1.00e+01 1.00e-01 1.50e+02]
 [1.00e+01 1.00e-01 1.60e+02]
 [1.00e+01

In [52]:
inputs.shape

(240, 3)

In [67]:
#read in outputs
outputs = []
for i in range(1,241):
    x = np.load(f"/home/nowickr/pnevo/PNevo/astr8070/npys_for_project_old/outputs_arr_{i}.npy")
    outputs.append(x[0])
print(outputs)

[array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array([nan]), array

In [68]:
#transpose into a column vector
outputs = np.array(outputs)
#outputs = outputs.T
print(outputs)

[[         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [         nan]
 [      

In [65]:
print(inputs)
print('--------------')
print(outputs)

[[4.00e+00 1.00e-01 1.20e+02]
 [4.00e+00 1.00e-01 1.50e+02]
 [4.00e+00 1.00e-01 1.60e+02]
 [4.00e+00 1.00e-01 1.70e+02]
 [4.00e+00 1.00e-01 1.75e+02]
 [5.00e+00 1.00e-01 1.20e+02]
 [5.00e+00 1.00e-01 1.50e+02]
 [5.00e+00 1.00e-01 1.60e+02]
 [5.00e+00 1.00e-01 1.70e+02]
 [5.00e+00 1.00e-01 1.75e+02]
 [6.00e+00 1.00e-01 1.20e+02]
 [6.00e+00 1.00e-01 1.50e+02]
 [6.00e+00 1.00e-01 1.60e+02]
 [6.00e+00 1.00e-01 1.70e+02]
 [6.00e+00 1.00e-01 1.75e+02]
 [7.00e+00 1.00e-01 1.20e+02]
 [7.00e+00 1.00e-01 1.50e+02]
 [7.00e+00 1.00e-01 1.60e+02]
 [7.00e+00 1.00e-01 1.70e+02]
 [7.00e+00 1.00e-01 1.75e+02]
 [8.00e+00 1.00e-01 1.20e+02]
 [8.00e+00 1.00e-01 1.50e+02]
 [8.00e+00 1.00e-01 1.60e+02]
 [8.00e+00 1.00e-01 1.70e+02]
 [8.00e+00 1.00e-01 1.75e+02]
 [9.00e+00 1.00e-01 1.20e+02]
 [9.00e+00 1.00e-01 1.50e+02]
 [9.00e+00 1.00e-01 1.60e+02]
 [9.00e+00 1.00e-01 1.70e+02]
 [9.00e+00 1.00e-01 1.75e+02]
 [1.00e+01 1.00e-01 1.20e+02]
 [1.00e+01 1.00e-01 1.50e+02]
 [1.00e+01 1.00e-01 1.60e+02]
 [1.00e+01

In [66]:
#join data
joint_data = np.hstack((inputs,outputs))
print(joint_data)

[[4.00000000e+00 1.00000000e-01 1.20000000e+02            nan]
 [4.00000000e+00 1.00000000e-01 1.50000000e+02            nan]
 [4.00000000e+00 1.00000000e-01 1.60000000e+02            nan]
 [4.00000000e+00 1.00000000e-01 1.70000000e+02            nan]
 [4.00000000e+00 1.00000000e-01 1.75000000e+02            nan]
 [5.00000000e+00 1.00000000e-01 1.20000000e+02            nan]
 [5.00000000e+00 1.00000000e-01 1.50000000e+02            nan]
 [5.00000000e+00 1.00000000e-01 1.60000000e+02            nan]
 [5.00000000e+00 1.00000000e-01 1.70000000e+02            nan]
 [5.00000000e+00 1.00000000e-01 1.75000000e+02            nan]
 [6.00000000e+00 1.00000000e-01 1.20000000e+02            nan]
 [6.00000000e+00 1.00000000e-01 1.50000000e+02            nan]
 [6.00000000e+00 1.00000000e-01 1.60000000e+02            nan]
 [6.00000000e+00 1.00000000e-01 1.70000000e+02            nan]
 [6.00000000e+00 1.00000000e-01 1.75000000e+02            nan]
 [7.00000000e+00 1.00000000e-01 1.20000000e+02         

In [27]:
#save the data as a file
pnevo_directory = f"/home/nowickr/pnevo/PNevo/astr8070/"
np_directory = f"{pnevo_directory}MPARs_for_Project/npy_outputs/"

np.save(f'{np_directory}TSP_dataset.npy',joint_data)